### ISSUE TITLE
Cannot import module @cortex-js/compute-engine

### ISSUE THREAD

**Issue by edward1127** [extremeheat/JSPyBridge#111]
Does anyone know how I can import module `@cortex-js/compute-engine`? 

I get a module node found error when importing that module. 

```
javascript.errors.JavaScriptError: ('require', "Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@cortex-js/compute-engine' imported from /home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/javascript/js/deps.js\n    at new NodeError (node:internal/errors:399:5)\n    at packageResolve (node:internal/modules/esm/resolve:783:9)\n 
```

**Comment by extremeheat** [comment]
Seems to work ok for me

![image](https://github.com/extremeheat/JSPyBridge/assets/13713600/60f2aebf-813c-4563-af8a-f540771d98a1)

If nessesary, you can use the CLI tool to manually install the package with
```
python -m javascript --install @cortex-js/compute-engine
```

**Comment by edward1127** [comment]
thanks for responding. Yep, I confirmed that it works when using it independently. Then, it seems like this package and Django are not compatible.
```
django==4.2
djangorestframework==3.14.0
```

**Comment by extremeheat** [comment]
There does seem to be a minor issue with ESM path resolution, potentially fixed in #115. But with or without Django, I don't notice any issues.

without - https://gist.github.com/extremeheat/c97ea38e8fb40921080ad97e2325a5b1
with - https://gist.github.com/extremeheat/db89aedb8cfcd76d31fecd5631613477

**Comment by edward1127** [comment]
I believe if you start the Django server, you will see the error.

```
python manage.py runserver

Watching for file changes with StatReloader
2023-12-15 18:28:20,629 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/edward/Desktop/arete/backend/core/urls.py", line 35, in <module>
    path('api/', include(('question_judge.urls', 'question_judge'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/edward/Desktop/arete/backend/question_judge/urls.py", line 3, in <module>
    from question_judge.views import (QuestionViewSet, QuestionSubmissionViewSet, SolutionViewSet,
  File "/home/edward/Desktop/arete/backend/question_judge/views.py", line 21, in <module>
    from question_judge.serializers import (
  File "/home/edward/Desktop/arete/backend/question_judge/serializers.py", line 8, in <module>
    from question_judge.utils import verify_answer
  File "/home/edward/Desktop/arete/backend/question_judge/utils.py", line 11, in <module>
    test = require('@cortex-js/compute-engine')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/javascript/__init__.py", line 37, in require
    return config.global_jsi.require(name, version, calling_dir, timeout=900)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/javascript/proxy.py", line 218, in __call__
    else self._exe.callProp(
         ^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/javascript/proxy.py", line 158, in callProp
    resp = self.pcall(ffid, "call", method, args, timeout=timeout, forceRefs=forceRefs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/javascript/proxy.py", line 146, in pcall
    raise JavaScriptError(attr, res["error"])
javascript.errors.JavaScriptError: ('require', "Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@cortex-js/compute-engine' imported from /home/edward/anaconda3/envs/arete/lib/python3.11/site-packages/javascript/js/deps.js\n    at new NodeError (node:internal/errors:399:5)\n    at packageResolve (node:internal/modules/esm/resolve:783:9)\n    at moduleResolve (node:internal/modules/esm/resolve:832:20)\n    at defaultResolve (node:internal/modules/esm/resolve:1069:11)\n    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:305:12)\n    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:156:32)\n    at DefaultModuleLoader.import (node:internal/modules/esm/loader:265:12)\n    at importModuleDynamically (node:internal/modules/cjs/loader:1185:37)\n    at importModuleDynamicallyWrapper (node:internal/vm/module:428:21)\n    at importModuleDynamically (node:internal/vm:105:46)")
```

**Comment by extremeheat** [comment]
What is the Python code that triggered this error?

**Comment by edward1127** [comment]
```
from javascript import require
test = require('@cortex-js/compute-engine')
```

**Comment by extremeheat** [comment]
Can you link to a notebook that reproduces the error?

**Comment by edward1127** [comment]
`pip install -r requirements.txt`
`python manage.py runserver`

running directly in sandbox will fail, so you might need to reproduce it by clone the code into your local and run the commands above. 

[sandbox](https://codesandbox.io/p/devbox/bitter-mountain-3s6xxr?file=%2Frequirements.txt%3A3%2C22&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq72vvkb00062v6jf5wm3q8h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq72vvkb00022v6jg3hzwwl0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq72vvkb00042v6jxzfbahwj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq72vvkb00052v6jbw0rhrrt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq72vvkb00022v6jg3hzwwl0%2522%253A%257B%2522id%2522%253A%2522clq72vvkb00022v6jg3hzwwl0%2522%252C%2522activeTabId%2522%253A%2522clq73piz300022v6jyyg4by56%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftutorial%252Fsettings.py%2522%252C%2522id%2522%253A%2522clq730vdv00h22v6jaqvqjleh%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clq73piz300022v6jyyg4by56%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Frequirements.txt%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clq72vvkb00052v6jbw0rhrrt%2522%253A%257B%2522id%2522%253A%2522clq72vvkb00052v6jbw0rhrrt%2522%252C%2522activeTabId%2522%253A%2522clq73r0kz006y2v6ji0708kd9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A8000%252C%2522id%2522%253A%2522clq73r0kz006y2v6ji0708kd9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clq72vvkb00042v6jxzfbahwj%2522%253A%257B%2522id%2522%253A%2522clq72vvkb00042v6jxzfbahwj%2522%252C%2522activeTabId%2522%253A%2522clq72wgsb003u2v6j8b425zzb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq72vvkb00032v6jtql6agbj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clq72wgsb003u2v6j8b425zzb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clq72wgvn00bxeehv85qj8q2e%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
