### ISSUE TITLE
Importing the module proceeds to just crash the code

### ISSUE THREAD

**Issue by Tyclonie** [extremeheat/JSPyBridge#118]
### Code: 

from javascript import require

### Error:

/usr/bin/python3.8 /home/ubuntu/projects/palmerbot/mc.py 
[JSE] /usr/local/lib/python3.8/dist-packages/javascript/js/bridge.js:14

[JSE] const debug = process.env.DEBUG?.includes('jspybridge') ? console.debug : () => { }

[JSE]                                 ^

[JSE] 

[JSE] SyntaxError: Unexpected token .

[JSE]     at Module._compile (internal/modules/cjs/loader.js:723:23)

[JSE]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

[JSE]     at Module.load (internal/modules/cjs/loader.js:653:32)

[JSE]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

[JSE]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

[JSE]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

[JSE]     at startup (internal/bootstrap/node.js:283:19)

[JSE]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

** The Node process has crashed. Please restart the runtime to use JS APIs. **

Timed out get 0 needsNodePatches None
Traceback (most recent call last):
  File "/home/ubuntu/projects/palmerbot/mc.py", line 1, in <module>
    from javascript import require
  File "/usr/local/lib/python3.8/dist-packages/javascript/__init__.py", line 20, in <module>
    init()
  File "/usr/local/lib/python3.8/dist-packages/javascript/__init__.py", line 16, in init
    if config.global_jsi.needsNodePatches():
  File "/usr/local/lib/python3.8/dist-packages/javascript/proxy.py", line 230, in __getattr__
    methodType, val = self._exe.getProp(self._pffid, attr)
  File "/usr/local/lib/python3.8/dist-packages/javascript/proxy.py", line 150, in getProp
    resp = self.ipc("get", ffid, method)
  File "/usr/local/lib/python3.8/dist-packages/javascript/proxy.py", line 43, in ipc
    raise Exception(f"Timed out accessing '{attr}'")
Exception: Timed out accessing 'needsNodePatches'

Process finished with exit code 1

**Comment by Tyclonie** [comment]
Sorry I believe this may be because of an older version of Node. I will update to at least 16 and hopefully this fixes the issue.

**Comment by Tyclonie** [comment]
Yep. Old version my apologies
