### ISSUE TITLE
 Rendering Error for Python-Defined React Components

### ISSUE THREAD

**Issue by arvindavoudi** [extremeheat/JSPyBridge#129]
# Error when Rendering React Component Defined as a Python Function for SSR Purposes
## Environment
OS: MacOS Sonoma 14.2.1 (Apple Silicon)
JSPyBridge Version: 1!1.1.3
Python Version: 3.11.7
Node.js Version: v20.11.1

## Description
Attempting to render a React component defined as a Python function using ReactDOMServer.renderToString() results in a JavaScript error, contrasting with the expected behavior where the component would be rendered similarly to its JavaScript equivalent. This issue suggests a discrepancy in how JSPyBridge handles the translation of Python-defined React components.

### Working Example in Python
```python
from javascript import require
React = require('react')
ReactDOMServer = require('react-dom/server')

renderedString = ReactDOMServer.renderToString(React.createElement('div', {}, 'Hello World!'))
print(renderedString)
```
#### Output:
```html
<div>Hello World!</div>
```
### Failing Example in Python
```python
from javascript import require
React = require('react')
ReactDOMServer = require('react-dom/server')

def SimpleDivComponent():
    return React.createElement('div', {}, 'Hello World!')

renderedString = ReactDOMServer.renderToString(React.createElement(SimpleDivComponent))
print(renderedString)
```
#### Error:

```
☕  JavaScript Error  Call to 'createElement' failed:
> renderedString = ReactDOMServer.renderToString(React.createElement(SimpleDivComponent))
  at <module> (/jsbridge_test/hi2.py:16)
> 

... across the bridge ...

  at Socket.<anonymous> (/opt/homebrew/lib/python3.11/site-packages/javascript/js/bridge.js:292:18)
  at Bridge.onMessage (/opt/homebrew/lib/python3.11/site-packages/javascript/js/bridge.js:231:25)
  at Bridge.call (/opt/homebrew/lib/python3.11/site-packages/javascript/js/bridge.js:136:42)
  at Object.createElementWithValidation [as createElement] (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2378:5)
  at validatePropTypes (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2274:7)
  at checkPropTypes (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2060:11)
  at setCurrentlyValidatingElement (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2025:19)
  at describeUnknownElementTypeFrameInDEV (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:1976:14)
  at describeNativeComponentFrame (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:1947:31)
  at describeBuiltInComponentFrame (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:1787:26)
> return '\n' + prefix + name;
🌉 TypeError: Cannot convert object to primitive value
[JSE] node:internal/process/promises:289

[JSE]             triggerUncaughtException(err, true /* fromPromise */);

[JSE]             ^

[JSE] 

[JSE] [🐍  Python Error  JavaScript attempt to call 'propTypes.callstack' in Python failed:

[JSE] > const stacktrace = new PythonException(stack)

[JSE]   at PyBridge.call (/opt/homebrew/lib/python3.11/site-packages/javascript/js/pyi.js:150:26)

[JSE]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

[JSE] 

[JSE] ... across the bridge ...

[JSE] 

[JSE] 🌉 LookupError: Property 'propTypes' does not exist on <function SimpleDivComponent at 0x100c06340>]

[JSE] 

[JSE] Node.js v20.11.1
```

### Equivalent Working Example in JavaScript
```javascript
const React = require('react');
const ReactDOMServer = require('react-dom/server');

const SimpleDivComponent = () => {
  return React.createElement('div', {}, 'Hello World!');
};

const renderedString = ReactDOMServer.renderToString(React.createElement(SimpleDivComponent));
console.log(renderedString);
```

#### Output:

```html
<div>Hello World!</div>
```

## Behavior Summary
Expected to render Python-defined React components similarly to JavaScript ones without errors, but rendering Python functions as React components via JSPyBridge results in a TypeError, highlighting a discrepancy in handling across languages.

## Additional Information
An attempt to patch propTypes of SimpleDivComponent with the following code was made to explore error details further:

```python
SimpleDivComponent.propTypes = {}
SimpleDivComponent.propTypes['callstack'] = lambda *args: print(args)
```

The error messages and a TypeError occur after this patch, but it provides insight into the failure process. The result of printing args is in front of `🌉 TypeError: Cannot convert object to primitive value`

```bash
☕  JavaScript Error  Call to 'createElement' failed:
> renderedString = ReactDOMServer.renderToString(React.createElement(SimpleDivComponent))
  at <module> (/jsbridge_test/hi2.py:16)
> 

... across the bridge ...

  at Socket.<anonymous> (/opt/homebrew/lib/python3.11/site-packages/javascript/js/bridge.js:292:18)
  at Bridge.onMessage (/opt/homebrew/lib/python3.11/site-packages/javascript/js/bridge.js:231:25)
  at Bridge.call (/opt/homebrew/lib/python3.11/site-packages/javascript/js/bridge.js:136:42)
  at Object.createElementWithValidation [as createElement] (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2378:5)
  at validatePropTypes (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2274:7)
  at checkPropTypes (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2060:11)
  at setCurrentlyValidatingElement (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:2025:19)
  at describeUnknownElementTypeFrameInDEV (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:1976:14)
  at describeNativeComponentFrame (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:1947:31)
  at describeBuiltInComponentFrame (/opt/homebrew/lib/python3.11/site-packages/javascript/js/node_modules/react/cjs/react.development.js:1787:26)
> return '\n' + prefix + name;
🌉 TypeError: Cannot convert object to primitive value({'callstack': (Some Python object)}, 'callstack', (Some Python object), 'prop', None, 'SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED')

[JSE] node:internal/process/promises:289

[JSE]             triggerUncaughtException(err, true /* fromPromise */);

[JSE]             ^

[JSE] 

[JSE] [🐍  Python Error  JavaScript attempt to call 'displayName' in Python failed:

[JSE] > if (resp.key === 'error') throw new PythonException(stack, resp.sig)

[JSE]   at PyBridge.value (/opt/homebrew/lib/python3.11/site-packages/javascript/js/pyi.js:177:37)

[JSE]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

[JSE] 

[JSE] ... across the bridge ...

[JSE] 

[JSE] 🌉 TypeError: 'function' object is not subscriptable]

[JSE] 

[JSE] Node.js v20.11.1
```

These observations suggest that the issue might be related to the handling of propTypes or the conversion of Python objects to a form that React expects.

The equivalent JavaScript code executed in Node.js works as expected, confirming that the issue is specific to the integration between Python functions and React components through JSPyBridge, rather than a general issue with React or the component definition itself.

No other modifications were made to the environment or the libraries involved. The investigation indicates a potential challenge in translating Python-defined React components for rendering, contrasting with their successful execution when defined in native JavaScript.

**Comment by extremeheat** [comment]
If you pass a Python function to one inside JavaScript, then the JavaScript side needs to `await` the result of the function. If the JS side doesn't await, then the function result will stay as a Promise and can yield other errors.

You can either use `eval_js` to embed JS into your code (like your JS snippet) or wrap the createElement calls to resolve the function on the Python side, without passing a function to JS.

see https://colab.research.google.com/gist/extremeheat/055f0f1b2104fb3f23e5ddea5c16889c/jspybridge-129.ipynb

**Comment by arvindavoudi** [comment]
Thanks! It works well.
