### ISSUE TITLE
Cannot manually re-initialize the bridge within the same Python process

### ISSUE THREAD

**Issue by Tales-Carvalho** [extremeheat/JSPyBridge#130]
Hi! I have a case where I would like to re-initialize the underlying NodeJS process to ensure I start communicating in a clean state, as I am running the bridge on many independent functions within a same Python process.

Currently if a JS call from Python times out and breaks the bridge, every subsequent JS call does not execute until I restart the Python process. I would like to restore the bridge dynamically when these exceptions are caught within Python.

I noticed that simply running `javascript.config.event_loop.stop()` and `javascript.init()` does not re-initialize the process cleanly, and subsequent JS calls fail to execute.

This is a minimal example that reproduces this issue:

```py
import javascript

javascript.eval_js('console.log("Hello from 1st NodeJS process!")')

javascript.config.event_loop.stop()
javascript.init()

javascript.eval_js('console.log("Hello from 2nd NodeJS process!")')
```

Which raises:
```
Traceback (most recent call last):
  File "JSPyBridge/src/test_minimal.py", line 6, in <module>
    javascript.init()
  File "JSPyBridge/src/javascript/__init__.py", line 9, in init
    config.event_loop = events.EventLoop()
                        ^^^^^^^^^^^^^^^^^^
  File "JSPyBridge/src/javascript/events.py", line 73, in __init__
    self.callbackExecutor.start()
  File "~/.pyenv/versions/3.11.7/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 959, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```

I noticed, however, that through small changes it is possible to achieve this behaviour. I will attach a PR to this issue describing a proposed set of changes that allows this behaviour and should not break the current interface of the module. I am open to discuss it further here if other solutions are preferable, though!

**Comment by Tales-Carvalho** [comment]
Thank you for merging my PR!
