### ISSUE TITLE
BridgeException [Error]: Attempt to access 'fileImport' failed. 

### ISSUE THREAD

**Issue by hailovigor** [extremeheat/JSPyBridge#150]
`BridgeException [Error]: Attempt to access 'fileImport' failed. Python didn't respond in time (100000ms), look above for any Python errors. If no errors, the API call hung.
proj/node_modules/pythonia/src/pythonia/Bridge.js:249:13
at waitFor (proj/node_modules/pythonia/src/pythonia/Bridge.js:124:26)
at Bridge.call (proj/node_modules/pythonia/src/pythonia/Bridge.js:234:18)
at InstProfileService.loginByDB (/proj/src/instProfile/instProfile.service.ts:174:32)
`

Hello. There is such an error in production. Please tell me what could be the solution?

**Comment by hailovigor** [comment]
The problem was most likely that in the PY file the function was launched immediately, which prevented it from being worked with from nodejs.

like this:
`def test:
     looongProcess();
     
 #for local test
 test()`
