### ISSUE TITLE
Attempting to load pdfjs library fails with syntax error

### ISSUE THREAD

**Issue by mara004** [extremeheat/JSPyBridge#47]
I would like to use the [`pdf.js`](https://github.com/mozilla/pdf.js) from Python. This is how I tried to load it using `JSPyBridge`:

```python3
>>> import javascript
>>> pdfjsLib = javascript.require("pdfjs-dist")
```

It fails with the following error:
```
Error in exception handler
[Errno 2] No such file or directory: 'internal/modules/cjs/loader.js'
** JavaScript Stacktrace **
/home/mara/node_modules/pdfjs-dist/build/pdf.js:2440
    return this._jsActionsPromise ||= this._transport.getPageJSActions(this._pageIndex);
                                  ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.$require [as require] (/home/mara/.local/lib/python3.8/site-packages/javascript/js/deps.js:128:15)
    at async Bridge.call (/home/mara/.local/lib/python3.8/site-packages/javascript/js/bridge.js:136:17)
** Python Stacktrace **
  File "<stdin>", line 1, in <module>

  File "/home/mara/.local/lib/python3.8/site-packages/javascript/__init__.py", line 37, in require
    return config.global_jsi.require(name, version, calling_dir, timeout=900)

  File "/home/mara/.local/lib/python3.8/site-packages/javascript/proxy.py", line 213, in __call__
    else self._exe.callProp(

  File "/home/mara/.local/lib/python3.8/site-packages/javascript/proxy.py", line 153, in callProp
    resp = self.pcall(ffid, "call", method, args, timeout=timeout, forceRefs=forceRefs)

  File "/home/mara/.local/lib/python3.8/site-packages/javascript/proxy.py", line 141, in pcall
    raise JavaScriptError(attr, res["error"])
```

**Comment by rom1504** [comment]
That error is "your node version is below 16"

**Comment by Heath123** [comment]
Try doing what the error says and use the legacy build, or Google the error. it doesn't look like it has anything to do with the bridge

**Comment by mara004** [comment]
[This thread](https://stackoverflow.com/questions/64189359/reading-pdf-from-url-with-node-js-using-pdf-js) looks related. I'll try the legacy build...

**Comment by mara004** [comment]
Yes, the legacy build helped. I am now able to invoke pdfjs using
```python3
>>> pdfjsLib = javascript.require("/home/mara/Downloads/builds/pdf.js/build/generic-legacy/build/pdf.js")
>>> loadingTask = pdfjsLib.getDocument("/home/mara/Downloads/Anderes/pdfs/test.pdf")
```

However, I'm wondering what is meant by `browser/environment` in the exception. What would I need to update in order to use the "normal" (non-legacy) build?

**Comment by rom1504** [comment]
I guess you'd need to use a browser

**Comment by mara004** [comment]
FWIW, this works now with the regular (non-legacy) build, outside of a browser. I'm on a newer OS and nodejs version these days. Perhaps my nodejs was just still too old?

**Comment by antont** [comment]
@mara004 seems that Node added ReadableStream quite recently, https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream
