### ISSUE TITLE
using pandas and DataFrame from JS

### ISSUE THREAD

**Issue by ikb42** [extremeheat/JSPyBridge#51]
const pd = await python('pandas')
    const df = await pd.DataFrame([{a:1,b:2},{a:123,b:234}])
        
    await df.apply$(pd.to_numeric);

I get:

    UnhandledPromiseRejectionWarning: Error: Attempt to access 'apply' failed. 
    Python didn't respond in time (100000ms)
    ...
    (node:32) UnhandledPromiseRejectionWarning: 
    *** PY ***  Python Error  Call to 'to_numeric.$timeout' failed:
    >     if (resp.key === 'error') throw new PythonException(stack, resp.sig)
      at Bridge.value (..\node_modules\pythonia\src\pythonia\Bridge.js:274:37)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

    ... across the bridge ...

    *** JS *** TypeError: 'function' object is not subscriptable

Not sure how to approach this?  Not a bug as such, but others may run into this so I thought it worth understanding.

**Comment by ikb42** [comment]
const $pdTo_numeric = await pd.to_numeric;
    await df.apply$({func: $pdTo_numeric});
